language: php
php:
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: 4d0d6ef7badae22d03d2ec1fcceef8e5d4f44d0e17be09ad9f5cc1f6f190de57

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/test-reporter

